### ISSUE TITLE
Cloudflare Kolkata [CCU] datacenter/CDN missing

### ISSUE THREAD

**Issue by AD2011** [stevesong/cloud_cdn_cache#2]
Cloudflare has a POP at Kolkata, India [CCU] as mentioned here: https://www.cloudflare.com/en-gb/network/#:~:text=Kathmandu%2C%20NP-,Kolkata%2C%20IN,-Kuala%20Lumpur%2C%20MY

Please add it.

**Comment by stevesong** [comment]
Hi Abir.  Thanks for pointing this out.  The Cloudflare Kolkata CDN is there on the map but unfortunately hidden under the Fastly CDN marker.  If you disable the Fastly CDN layer, you will see it.  I am going to introduce some very modest randomization in the lat/lon of the CDN locations so that this kind of overlap doesn't happen any more.

**Comment by stevesong** [comment]
fwiw, I have re-done the Cloudflare map.  You shouldn't have to disable layers now to see the CF node for Kolkata.
